using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Text;

namespace SolarMaxClient.Protocol
{
    internal enum SolarMaxCommandEnum
    {
        [Description("DMO")]
        DEVICE_MODE,
        [Description("RAV")]
        NOMINAL_VOLTAGE,
        [Description("FMO")]
        RATED_FREQUENCY,
        [Description("UPD")]
        UPDATE_COMMAND,
        [Description("RST")]
        REBOOT,
        [Description("CLX")]
        RESTORE_FACTORY_SETTINGS,
        [Description("SYS")]
        DEVICE_STATUS,
        [Description("ADR")]
        DEVICE_ADDRESS,
        [Description("ETH")]
        ENABLE_ETHERNET,
        [Description("IP4")]
        IP_ADDRESS,
        [Description("SNM")]
        SUBNET_MASK,
        [Description("TCP")]
        TCP_PORT,
        [Description("MAC")]
        MAC_ADDRESS,
        [Description("DIN")]
        SERIAL_NUMBER,
        [Description("BDN")]
        BUILD_NUMBER,
        [Description("TYP")]
        DEVICE_TYPE,
        [Description("PIN")]
        INSTALLED_POWER,
        [Description("PAM")]
        MAXIMUM_POWER,
        [Description("0.5D")]
        POWER_RESOLUTION,
        [Description("UL1")]
        U_AC_L1,
        [Description("UL2")]
        U_AC_L2,
        [Description("UL3")]
        U_AC_L3,
        [Description("IL1")]
        I_AC_L1,
        [Description("IL2")]
        I_AC_L2,
        [Description("IL3")]
        I_AC_L3,
        [Description("UD01")]
        U_DC_L1,
        [Description("UD02")]
        U_DC_L2,
        [Description("UD03")]
        U_DC_L3,
        [Description("ID01")]
        I_DC_L1,
        [Description("ID02")]
        I_DC_L2,
        [Description("ID03")]
        I_DC_L3,
        [Description("UM1")]
        U_AC_10_MIN_MEAN_L1,
        [Description("UM2")]
        U_AC_10_MIN_MEAN_L2,
        [Description("UM3")]
        U_AC_10_MIN_MEAN_L3,
        [Description("UAC")]
        U_AC,
        [Description("IAC")]
        I_AC,
        [Description("UAM")]
        U_AC_10_MIN_MEAN,
        [Description("MOD")]
        NUMBER_OF_MODULE_STRINGS,
        [Description("SDAT")]
        DATE_TIME,
        [Description("DATE")]
        DATE,
        [Description("TIME")]
        TIME,
        [Description("DYR")]
        YEAR,
        [Description("DMT")]
        MONTH,
        [Description("DDY")]
        DAY,
        [Description("THR")]
        HOUR,
        [Description("TMI")]
        MINUTE,
        [Description("PAC")]
        P_AC,
        [Description("PAE")]
        P_AC_EFF,
        [Description("TNF")]
        FREQUENCY,
        [Description("TNP")]
        GRID_PERIOD,
        [Description("KDY")]
        ENERGY_DAY,
        [Description("KMT")]
        ENERGY_MONTH,
        [Description("KYR")]
        ENERGY_YEAR,
        [Description("KT0")]
        ENERGY_TOTAL,
        [Description("KLD")]
        ENERGY_LAST_DAY,
        [Description("KLM")]
        ENERGY_LAST_MONTH,
        [Description("KLY")]
        ENERGY_LAST_YEAR,
        [Description("RAD")]
        IRRADIATION,
        [Description("SAL")]
        STATUS_ALARM,
        [Description("SAL")]
        WARNINGS,
        [Description("DD{0:00}")]
        STATISTIC_DAY_NN,
        [Description("DM{0:00}")]
        STATISTIC_MONTH_NN,
        [Description("DY{0:00}")]
        STATISTIC_YEAR_NN,
        [Description("DD00")]
        STATISTIC_DAY_ENTRY_0,
        [Description("DM00")]
        STATISTIC_MONTH_ENTRY_0,
        [Description("DY00")]
        STATISTIC_YEAR_ENTRY_0,
        [Description("EC{0}")]
        STATUS_LOG_ENTRY_N,
        [Description("EC00")]
        STATUS_LOG_ENTRY_0,
        [Description("EL{0:00}")]
        ERROR_LOG_ENTRY_N,
        [Description("EL00")]
        ERROR_LOG_ENTRY_0,
        [Description("EL01")]
        ERROR_LOG_ENTRY_1,
        [Description("EL02")]
        ERROR_LOG_ENTRY_2,
        [Description("E{0:0}1")]
        ERROR_N_EC_1,
        [Description("E{0:0}2")]
        ERROR_N_EC_2,
        [Description("E{0:0}D")]
        ERROR_N_DAY,
        [Description("E{0:0}h")]
        ERROR_N_HOUR,
        [Description("E{0:0}m")]
        ERROR_N_MINUTE,
        [Description("E{0:0}M")]
        ERROR_N_MONTH,
        [Description("E11")]
        ERROR_1_EC_1,
        [Description("E12")]
        ERROR_1_EC_2,
        [Description("E1D")]
        ERROR_1_DAY,
        [Description("E1h")]
        ERROR_1_HOUR,
        [Description("E1m")]
        ERROR_1_MINUTE,
        [Description("E1M")]
        ERROR_1_MONTH,
        [Description("SCD")]
        STATUS_COMMAND,
        [Description("SDP")]
        STATUS_DSP_TO_PIC,
        [Description("SE1")]
        STATUS_ERROR_1,
        [Description("SE2")]
        STATUS_ERROR_2,
        [Description("SPC")]
        STATUS_SYSTEM,
        [Description("SPR")]
        STATUS_POWER,
        [Description("TKK")]
        TEMPERATURE_MAXIMUM,
        [Description("TK1")]
        TEMPERATURE_POWER_UNIT_1,
        [Description("CYC")]
        COUNTRY_CODE,
        [Description("STDP")]
        STANDARD_P_SERIES,
        [Description("GCP")]
        GRID_CONNECTION_POINT,
        [Description("PPO")]
        PLANT_POWER_RATING,
        [Description("GBS")]
        GREAT_BRITAIN_STANDARD,
        [Description("ITN")]
        ITALY_STANDARD,
        [Description("ESS")]
        SPAIN_STANDARD,
        [Description("PLF")]
        FREQUENCY_POWER_LIMITATION,
        [Description("FAN")]
        FAN,
        [Description("FSR")]
        FAN_STATE_REGISTER,
        [Description("RPR")]
        REACTIVE_POWER_REALTIVE,
        [Description("CPA")]
        COS_PHI_ABSOLUTE,
        [Description("PFA")]
        PHASE_DIFFERENCE_ANGLE,
        [Description("DRIP")]
        DEBUG_HOST_IP,
        [Description("DIAG")]
        ENABLE_DIAGNOSIS,
        [Description("NATM")]
        NA_SCHUTZ_TEST_MODE
    }
}
